* Fate

  *Keep track of what the gods have whispered you to do while you're
  on your computer*

  There's too much distraction in a computer, even when you're using
  the amazing [[https://github.com/ch11ng/exwm][EXWM]] environment, you can't help yourself and stop
  whatever you're doing to [[https://www.reddit.com/r/spiders/comments/3g6l8c/how_far_do_spiders_see/][read about how far spiders can see]].

  There's no way. Caos comes from within, from the wishes of the gods
  of Olympus. We mortals are left with our fate that can only be
  observed. And as mortals, we build tools for anything we can
  possibly do, so we don't have to do them ourselves.

  Fate is a tool for mortals to visualize what gods have told them to
  do while they're at the computer.

* How fate is decided

  As mortals that use computers, we all need to express caos within us
  and we keep trying to do more than one thing at a time. Fate is an
  [[https://www.gnu.org/software/emacs/][Emacs]] extension that watches all the commands executed while mortals
  use Emacs. When the mortal switches buffers, fate records the
  switching event an it's written in a file (=~/.fate.db= by default.)

  Whenever the mortal wants to read the whispers of the gods they can
  use the tools in the *analyze* directory to see what they've been up
  to.

